inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

AllCops:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/setup'
    - 'bin/update'
    - 'bin/yarn'
    - 'bin/webpack'
    - 'bin/webpack-dev-server'
    - 'db/schema.rb'
    - 'node_modules/**/*'

Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Rails/HelperInstanceVariable:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: false
