language: ruby
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
git:
  depth: false
install:
- bundle install
- nvm install node
- node -v
- npm i -g yarn
- yarn
script:
- bundle exec rails webpacker:compile
- bundle exec rails spec
- bundle exec govuk-lint-ruby app config db lib spec --format clang
- bundle exec govuk-lint-sass app/assets/stylesheets
env:
  global:
  - secure: puDeqECzb42+VMBoD73s7er0upc7sRr4aoItO5dPgJhBGCHGTtuMxkat2JRKJfW77I9eM+kFsCwOsmXkEWR+PJFDCMeQaNGJFrr4mHvrZ9/Zb3I44UCbUfwHMqYDgfkKzI3JO1CXoHicoqBdv402tXWHvf8W4wE6l54KH6DinCCnG0J5Fd7uNAMurNvan2OimHfyKKgiTIrq4bKDvtES9iTkinPsqeU6GH4jWGg5PGroqtBkn3Eikn0vQYWYvlBEUvNnIG+o3pVa35ecfOIu5lwNou7Ts06+KRoZGLlJueuWL6MKy1Hvf84eYw1LfjMtQat3VDZR5DONvHfKllNNjVq9YX3QxQeE7F/k0C6FaJCDsuUCF2HhwFvkM5EDmjCXUFXmnZJBjtda9+OY28iGMoy/P8RKKVUO/R3KZhtzfw5NwmjchLKgWMnFqB55UdIv8hdfQZeNmjJzFA1OUayi4KNaapZUYXSrkgYi7XZmM6cN+10Wq5FFAt90ldbf1qngPdnohWT5td5a0Qb5OYl4lPMZa4EnUztbmpcrcxaDynaE6HmZjqnfZULicyYdLt9QaeS+1Dtdbe92gm4L+5x2lsLc7FOZFUrsdJNaIfut/3xJMV/FqHbyh53XuLmJf8g5AGPxfDdoFF0T8EC+m8Yr1+4cnfjWl5cUla4woeHyTOc=
deploy:
- provider: script
  script: git push --force https://govuk-dfe-bat-deployment-user:$AZURE_WA_PASSWORD@bat-dev-manage-courses-frontend-app.scm.azurewebsites.net:443/bat-dev-manage-courses-frontend-app.git
    HEAD:refs/heads/master
  on: master
- provider: script
  script: git push --force https://govuk-dfe-bat-deployment-user:$AZURE_WA_PASSWORD@bat-staging-manage-courses-frontend-app.scm.azurewebsites.net:443/bat-staging-manage-courses-frontend-app.git
    HEAD:refs/heads/master
  on: staging
- provider: script
  script: 
  - git push --force https://govuk-dfe-bat-deployment-user:$AZURE_WA_PASSWORD@bat-prod-manage-courses-frontend-app.scm.azurewebsites.net:443/bat-prod-manage-courses-frontend-app.git HEAD:refs/heads/master
  - git push --force https://govuk-dfe-bat-deployment-user:$AZURE_WA_PASSWORD@bat-prod3-manage-courses-frontend-app.scm.azurewebsites.net:443/bat-prod3-manage-courses-frontend-app.git HEAD:refs/heads/master
  on: production
