version: "3"

services:
  web:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    command: rails s -b 'ssl://web:3000?key=config/localhost/https/localhost.key&cert=config/localhost/https/localhost.crt'
