default: &default
  ASSETS_PRECOMPILE: true
  RAILS_SERVE_STATIC_FILES: true
  WEBPACKER_DEV_SERVER_HOST: "webpacker"
  SETTINGS__FEATURES__DFE_SIGNIN: true
  SETTINGS__FEATURES__SIGNIN_BY_EMAIL: false
  SETTINGS__FEATURES__SIGNIN_INTERCEPT: false
  SETTINGS__ROLLOVER: false

qa:
  <<: *default
  RAILS_ENV: qa
  RACK_ENV: qa

staging:
  <<: *default
  RAILS_ENV: staging
  RACK_ENV: staging

prod:
  <<: *default
  RAILS_ENV: production
  RACK_ENV: production
