dfe_signin:
  # Our service name
  identifier: bats2
  # URL that the users are redirected to for signing in
  issuer: https://signin-test-oidc-as.azurewebsites.net
  # URL of the users profile
  profile: https://signin-test-pfl-as.azurewebsites.net
  # This value must be set otherwise sign in will fail
  secret: foobar
  # URL of this app for the callback after sigining in
  base_url: https://localhost:3000
authentication:
  algorithm: HS256
  # Set this in the env! The below ensures that we are un-authenticatable if we
  # forget to do this in production.
  secret: <%= SecureRandom.base64 %>
manage_backend:
  # URL of the API app (manage-courses-backend)
  base_url: http://localhost:3001
manage_ui:
  # URL of the c# ui app (manage-courses-ui)
  base_url: https://localhost:44364
search_ui:
  # URL of the C# search ui app (search-and-compare-ui)
  base_url: https://localhost:5000
google_forms:
  new_course_for_accredited_bodies_url: https://docs.google.com/forms/d/e/1FAIpQLSd4k5wSjrVyFu-FW4ZaSsrbK0AwTpjmzfyTdfa_qdXLZ313HQ/viewform
  new_course_for_unaccredited_bodies_url: https://docs.google.com/forms/d/e/1FAIpQLSeatJO2ZuqM-fnRJxEo6IIF0hZIU63JGnx0sDXO6Ulax7U_bA/viewform
  add_location_url: https://docs.google.com/forms/d/e/1FAIpQLSeW14NPB081ZwayBStlZsmCoKycFuhwtktozbu8MF7CWpm5Og/viewform
service_support:
  contact_email_address: becomingateacher@digital.education.gov.uk
