dfe_signin:
  secret: please_change_me # Override with SETTINGS__DFE_SIGNIN__SECRET
  base_url: https://localhost:3000
features:
  allocations:
    # state: open # Users can make requests for allocations
    # state: closed # Readonly - Users can see if they have or have not made request (does not show number of places)
    state: confirmed # final allocation places are displayed to users in a readonly state
teacher_training_api:
  secret: secret
  base_url: http://localhost:3001
search_ui:
  base_url: https://localhost:5000
environment:
  label: "Development"
  selector_name: "development"
log_level: debug
use_ssl: false
basic_auth: false
developer_auth: true
