dfe_signin:
  issuer: https://signin-test-oidc-as.azurewebsites.net
  profile: https://signin-test-pfl-as.azurewebsites.net
  secret: please_change_me # Override with SETTINGS__DFE_SIGNIN__SECRET
  base_url: https://bat-stg-mcfe-as.azurewebsites.net
manage_backend:
  base_url: https://bat-stg-mcbe-as.azurewebsites.net
manage_ui:
  base_url: https://bat-stg-mcui-as.azurewebsites.net
search_ui:
  base_url: https://bat-stg-sacui-as.azurewebsites.net
environment:
  label: 'Staging'
  class_name: 'staging'
