dfe_signin:
  issuer: https://signin-test-oidc-as.azurewebsites.net
  profile: https://signin-test-pfl-as.azurewebsites.net
  secret: please_change_me # Override with SETTINGS__DFE_SIGNIN__SECRET
  base_url: https://www2.dev.publish-teacher-training-courses.service.gov.uk
manage_backend:
  base_url: https://api2.dev.publish-teacher-training-courses.service.gov.uk
manage_ui:
  base_url: https://www.dev.publish-teacher-training-courses.service.gov.uk
search_ui:
  base_url: https://www.dev.find-postgraduate-teacher-training.service.gov.uk
