dfe_signin:
  issuer: https://signin-test-oidc-as.azurewebsites.net
  profile: https://signin-test-pfl-as.azurewebsites.net
  secret: please_change_me # Override with PTT__DFE_SIGNIN__SECRET
  base_url: https://www.pen.publish-teacher-training-courses.service.gov.uk
  user_search_url: https://signin-test-sup-as.azurewebsites.net/users
manage_backend:
  base_url: https://api2.pen.publish-teacher-training-courses.service.gov.uk
search_ui:
  base_url: https://www.pen.find-postgraduate-teacher-training.service.gov.uk
environment:
  label: "QA"
  selector_name: "qa"
