dfe_signin:
  secret: please_change_me # Override with SETTINGS__DFE_SIGNIN__SECRET
  base_url: https://www.pen.publish-teacher-training-courses.service.gov.uk
manage_backend:
  base_url: https://api2.pen.publish-teacher-training-courses.service.gov.uk
search_ui:
  base_url: https://www.pen.find-postgraduate-teacher-training.service.gov.uk
environment:
  label: "QA"
  selector_name: "qa"
