teacher_training_api:
  base_url: https://teacher-training-api-rollover.london.cloudapps.digital
search_ui:
  base_url: https://find-rollover.london.cloudapps.digital
environment:
  label: "Review"
  selector_name: "review"
authentication:
  mode: persona
features:
  rollover:
    # During rollover providers should be able to edit current & next recruitment cycle courses
    can_edit_current_and_next_cycles: true
    # Normally a short period of time between rollover and the next cycle
    # actually starting when it would be set to false
    show_next_cycle_allocation_recruitment_page: true
  allocations:
    state: open
