teacher_training_api:
  base_url: https://qa.api.publish-teacher-training-courses.service.gov.uk
search_ui:
  base_url: https://qa.find-postgraduate-teacher-training.service.gov.uk
environment:
  label: "Review"
  selector_name: "review"
authentication:
  mode: persona
