publish_url: https://publish-teacher-training-rollover.london.cloudapps.digital

dfe_signin:
  issuer: https://pp-oidc.signin.education.gov.uk
  profile: https://pp-profile.signin.education.gov.uk
  secret: please_change_me # Override with SETTINGS__DFE_SIGNIN__SECRET
  base_url: https://publish-teacher-training-rollover.london.cloudapps.digital
  user_search_url: https://pp-support.signin.education.gov.uk/users
teacher_training_api:
  base_url: https://teacher-training-api-rollover.london.cloudapps.digital
search_ui:
  base_url: https://find-rollover.london.cloudapps.digital
environment:
  label: "Rollover"
  selector_name: "rollover"
features:
  rollover:
    # During rollover providers should be able to edit current & next recruitment cycle courses
    can_edit_current_and_next_cycles: true
    # Normally a short period of time between rollover and the next cycle
    # actually starting when it would be set to false
    has_current_cycle_started?: false
    show_next_cycle_allocation_recruitment_page: true
