dfe_signin:
  issuer: https://signin-test-oidc-as.azurewebsites.net
  profile: https://signin-test-pfl-as.azurewebsites.net
  secret: please_change_me # Override with SETTINGS__DFE_SIGNIN__SECRET
  base_url: https://bat-staging-manage-courses-frontend-app.azurewebsites.net
manage_backend:
  base_url: https://bat-staging-manage-courses-backend-app.azurewebsites.net
manage_ui:
  base_url: https://bat-staging-manage-courses-ui-app.azurewebsites.net
search_ui:
  base_url: https://bat-staging-search-and-compare-ui-app.azurewebsites.net
environment:
  label: 'Staging'
  selector_name: 'staging'
rollover: false
