dfe_signin:
  issuer: https://signin-test-oidc-as.azurewebsites.net
  profile: https://signin-test-pfl-as.azurewebsites.net
  secret: please_change_me # Override with SETTINGS__DFE_SIGNIN__SECRET
  base_url: https://bat-ucas-mcfe-as.azurewebsites.net
  identifier: batsucas
manage_backend:
  base_url: https://bat-ucas-mcbe-as.azurewebsites.net
manage_ui:
  base_url: https://bat-ucas-mcui-as.azurewebsites.net
search_ui:
  base_url: https://bat-ucas-sacui-as.azurewebsites.net
