name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: dfedigital/publish-teacher-training

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set environment variables
      run: |
        GIT_REF=${{ github.ref }}
        GIT_BRANCH=${GIT_REF##*/}
        echo "BRANCH_TAG=paas-$GIT_BRANCH" >> $GITHUB_ENV
        echo "DOCKER_IMAGE_TAG=paas-$GITHUB_SHA" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Publish Teacher Training
      uses: docker/build-push-action@v2.1.0
      with:
        tags: |
          ${{ env.DOCKER_IMAGE}}:${{ env.DOCKER_IMAGE_TAG }}
          ${{ env.DOCKER_IMAGE}}:${{ env.BRANCH_TAG }}
        pull: true
        push: true
        cache-from: |
          ${{ env.DOCKER_IMAGE}}:${{ env.BRANCH_TAG }}
          ${{ env.DOCKER_IMAGE}}:${{ env.DOCKER_IMAGE_TAG }}
        build-args: BUILDKIT_INLINE_CACHE=1

    - name: Trigger QA Deployment
      if: ${{ success() && github.ref == 'refs/heads/master' }}
      uses: benc-uk/workflow-dispatch@v1.1
      with:
        workflow: Deploy
        token: ${{ secrets.ACTIONS_API_ACCESS_TOKEN  }}
        inputs: '{"environment": "qa", "sha": "${{ github.sha }}"}'
