name: Build

on:
  push:
    branches:
      - master
      - qa
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: dfedigital/publish-teacher-training

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set environment variables
      run: |
        GIT_REF=${{ github.ref }}
        GIT_BRANCH=${GIT_REF##*/}
        echo "BRANCH_TAG=paas-$GIT_BRANCH" >> $GITHUB_ENV
        echo "DOCKER_IMAGE_TAG=paas-$GITHUB_SHA" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Publish Teacher Training
      uses: docker/build-push-action@v2.1.0
      with:
        tags: |
          ${{ env.DOCKER_IMAGE}}:${{ env.DOCKER_IMAGE_TAG }}
          ${{ env.DOCKER_IMAGE}}:${{ env.BRANCH_TAG }}
        pull: true
        push: true
        cache-from: |
          ${{ env.DOCKER_IMAGE}}:${{ env.BRANCH_TAG }}
          ${{ env.DOCKER_IMAGE}}:${{ env.DOCKER_IMAGE_TAG }}
        build-args: |
          BUILDKIT_INLINE_CACHE=1
          COMMIT_SHA=paas-${{ github.sha }}

    - name: Trigger Review App Deployment
      if: ${{ success() && github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Deploy
        ref:    ${{ github.head_ref }}
        token:  ${{ secrets.ACTIONS_API_ACCESS_TOKEN  }}
        inputs: '{"pr": "${{ github.event.pull_request.number }}", "sha": "${{ github.sha }}"}'

  test:
    runs-on: ubuntu-latest
    needs: [build]
    container: dfedigital/publish-teacher-training:paas-${{ github.sha }}
    defaults:
      run:
        working-directory: /app
    steps:
      - uses: softprops/turnstyle@v1
        name: Wait for other inprogress deployment runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Ruby Linting
        run:  rubocop app config lib spec --format clang

      - name: Sass Linting
        run:  scss-lint app/webpacker/stylesheets

      - name: Ruby Tests
        run:  rake parallel:spec

      - name: Run Javascript Tests
        run:  yarn test --coverage

      - name: Run Brakeman static analysis
        run:  rails brakeman

      - name: Trigger Deployment
        if: ${{ success() && github.ref == 'refs/heads/master' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy
          token: ${{ secrets.ACTIONS_API_ACCESS_TOKEN  }}
          inputs: '{"qa": "true", "staging": "true", "production": "true", "sandbox": "true", "rollover": "true", "sha": "${{ github.sha }}"}'

      - name: 'Notify #twd_publish_register_tech on failure'
        if: ${{ failure() && github.ref == 'refs/heads/master' }}
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: twd_publish_register_tech
          SLACK_COLOR: '#ef5343'
          SLACK_ICON_EMOJI: ':github-logo:'
          SLACK_USERNAME: Publish Teacher Training
          SLACK_TITLE: Build Failure
          SLACK_MESSAGE: ':alert: <!channel> Build failure'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
