name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to eg: qa, staging or production'
        required: true
      sha:
        description: Commit sha to be deployed
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/turnstyle@v1
        name: Wait for other inprogress deployment runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Start ${{ github.event.inputs.environment }} Deployment
        uses: bobheadxi/deployments@v0.4.2
        id: deployment
        with:
          env:   ${{ github.event.inputs.environment }}
          ref:   ${{ github.event.inputs.sha }}
          step:  start
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Terraform v0.13.5
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5

      - name: Set environment variables
        run: |
          echo "DOCKER_IMAGE=$DOCKER_IMAGE" >> $GITHUB_ENV
          echo "DEPLOY_ENV=$DEPLOY_ENV" >> $GITHUB_ENV
        env:
          DEPLOY_ENV:   ${{ github.event.inputs.environment }}
          DOCKER_IMAGE: ${{ format('dfedigital/publish-teacher-training:paas-{0}', github.event.inputs.sha) }}

      - name: Download app secrets file
        working-directory: terraform/workspace_variables
        run: echo $APP_SECRETS | base64 -d >> app_secrets.yml
        env:
          APP_SECRETS: ${{ secrets[format('APP_SECRETS_{0}', env.DEPLOY_ENV)] }}

      - name: Terraform init, plan & apply
        run: |
          terraform init -backend-config workspace_variables/${{ env.DEPLOY_ENV }}_backend.tfvars
          terraform plan -var-file workspace_variables/${{ env.DEPLOY_ENV }}.tfvars -out tfplan
          terraform apply -auto-approve -input=false "tfplan"
        env:
          ARM_ACCESS_KEY:             ${{ secrets[format('ARM_ACCESS_KEY_{0}', env.DEPLOY_ENV)] }}
          TF_VAR_dockerhub_username:  ${{ secrets.DOCKERHUB_USERNAME }}
          TF_VAR_dockerhub_password:  ${{ secrets.DOCKERHUB_PASSWORD }}
          TF_VAR_paas_docker_image:   ${{ env.DOCKER_IMAGE }}
          TF_VAR_cf_user:             ${{ secrets[format('CF_USERNAME_{0}', env.DEPLOY_ENV)] }}
          TF_VAR_cf_user_password:    ${{ secrets[format('CF_PASSWORD_{0}', env.DEPLOY_ENV)] }}
          TF_VAR_statuscake_username: ${{ secrets.STATUSCAKE_USERNAME }}
          TF_VAR_statuscake_password: ${{ secrets.STATUSCAKE_API_KEY }}

      - name: Update ${{ github.event.inputs.environment }} status
        if: ${{ always() }}
        uses: bobheadxi/deployments@v0.4.2
        with:
          env:  ${{ github.event.inputs.environment }}
          ref:  ${{ github.event.inputs.sha }}
          step: finish
          token:  ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
